# Generated by Django 5.0.6 on 2024-05-16 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect', '0004_alter_order_products_user_cart_alter_order_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_review', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proect.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proect.product')),
            ],
        ),
    ]
