# Generated by Django 5.0.6 on 2024-05-18 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
