# Generated by Django 5.0.6 on 2024-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect', '0006_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, default='https://avatars.mds.yandex.net/i?id=4e2584ffe6be91882307ebaff5ac63a1f173f9fb-11526326-images-thumbs&n=13'),
        ),
    ]
